

SELECT distinct ?item ?itemLabel ?itemDescription WHERE {  
  ?item ?label ?_label_str_iri@en.  
  ?article schema:about ?item .
  ?article schema:inLanguage "en" .
  ?article schema:isPartOf <https://en.wikipedia.org/>. 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }    
}
