#+ summary: Find Wikidata entities by label substring
#+ endpoint: https://query.wikidata.org/sparql
#+ method: GET

#+ defaults:
#+   - label_str: example

PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX schema: <http://schema.org/>

SELECT distinct ?item ?itemLabel ?itemDescription WHERE {  
  ?item ?label ?_label_str .  
  ?article schema:about ?item .
  ?article schema:inLanguage "en" .
  ?article schema:isPartOf <https://en.wikipedia.org/>. 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }    
}
