#+ summary: List all properties and their values for a Wikidata entity.
#+ endpoint: https://query.wikidata.org/sparql
#+ method: GET

#+ defaults:
#+   - qid: example

PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX schema: <http://schema.org/>
PREFIX wd: <http://www.wikidata.org/entity/>


SELECT ?property ?propertyLabel ?object (COALESCE(?valueLabel, STR(?o)) AS ?value) WHERE {
  ?property wikibase:directClaim ?p;
            rdfs:label ?propertyLabel filter (lang(?propertyLabel) = "en").
  ?_qid_iri ?p ?object.
  
  OPTIONAL {
    ?o rdfs:label ?valueLabel filter (lang(?valueLabel) = "en").
  }
  FILTER(!CONTAINS(LCASE(?propertyLabel), "id"))
  
}
